TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.15
  max_vel_y: 0
  min_vel_y: 0
  max_vel_theta: 5.0
  min_vel_theta: -5.0
  min_in_place_vel_theta: 1.5

  acc_lim_theta: 3.2
  acc_lim_x: 1.5
  acc_lim_y: 0

  escape_vel: -0.2

  holonomic_robot: false

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2