recovery_behaviors:
  - name: conservative_reset
    type: nav_core/ClearCostmapRecovery
  - name: rotate_recovery
    type: nav_core/RotateRecovery
  - name: aggressive_reset
    type: nav_core/ClearCostmapRecovery
recovery_behavior_enabled: false