recovery_behaviors:
  - name: conservative_reset
    type: clear_costmap_recovery/ClearCostmapRecovery
  - name: rotate_recovery
    type: rotate_recovery/RotateRecovery
  - name: aggressive_reset
    type: clear_costmap_recovery/ClearCostmapRecovery
recovery_behavior_enabled: false